//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> EmpSalary { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
    }
}
